Repository redb0/python-bp, pull requests merged in 2021-07, with the labels that each got.

#3 fixed links in classes section
  README.md
Labels: bug

#6 close issue rename file
  CONTRIBUTING.md
  python_pd/work/syntax/README.md
  python_pd/work/syntax/fizzbuzz/README.md
Labels: documentation, good first issue

#8 Libraries
  README.md
  libraries.md
Labels: enhancement, good first issue
